[pmbootstrap]
aports = HOME/.local/var/pmbootstrap/cache_git/pmaports
device = nothing-spacewar
jobs = NPROC
kernel = stable
user = user
work = HOME/.local/var/pmbootstrap
hostname = titago
ui = gnome-mobile
systemd = never
[providers]

[mirrors]
